import Foundation

/**
 Represents a unit of trackable content in your marketplace.
 For better conceptualization in your coed, prefer to use one of
 the subclasses (such as `Item` or `Partner`) instead of `Content`
 if they apply.
 */
@objc(PROContent)
public class Content: NSObject {

  /// Unique ID for this content. Can be an internal ID from your system.
  @objc public var contentID: String?

  /// Insertion ID as generated by Promoted.
  @objc public var insertionID: String?
  
  /// Initializes with nil `contentID` and nil `insertionID`.
  @objc public override init() {
    self.contentID = nil
    self.insertionID = nil
  }
  
  /// Initializes with the given `contentID` and nil `insertionID`.
  @objc public init(contentID: String) {
    self.contentID = contentID
    self.insertionID = nil
  }
  
  /// Initializes with the given `contentID` and `insertionID`.
  @objc public init(contentID: String, insertionID: String) {
    self.contentID = contentID
    self.insertionID = insertionID
  }
  
  /// Initializes with given dictionary as used to represent
  /// a piece of content, using the key arrays to read the dictionary.
  /// If the given properties do not contain a content ID, `contentID`
  /// will be `nil`. If the properties do not contain an insertion
  /// ID, `insertionID` will be nil.
  ///
  /// - Parameters:
  ///   - properties: Dictionary of properties to read from.
  ///   - contentIDKeys: Keys used to read `contentID`, in preferred
  ///     order.
  ///   - insertionIDKeys: Keys used to read `insertionID`, in
  ///     preferred order.
  @objc public init(properties: [String: Any]?,
                    contentIDKeys: [String],
                    insertionIDKeys: [String]) {
    self.contentID = properties?.firstValueFromKeysInArray(contentIDKeys)
    self.insertionID = properties?.firstValueFromKeysInArray(insertionIDKeys)
  }
  
  public override func isEqual(_ object: Any?) -> Bool {
    if let other = object as? Content {
      return self.contentID == other.contentID
    }
    return false
  }
  
  public override var hash: Int {
    return contentID?.hash ?? 0
  }
}

/** Represents a saleable unit in your marketplace. */
@objc(PROItem)
public class Item: Content {}

/**
 Represents a partner (store, restaurant, creator, etc.)
 that sells in your marketplace.
 */
@objc(PROPartner)
public class Partner: Content {}
