// swift-tools-version:5.3

import PackageDescription

let package = Package(
  name: "PromotedAIMetricsSDK",
  products: [
    .library(
      name: "PromotedAIMetricsSDK",
      targets: [
        "PromotedAIMetricsSDK",
      ]),
  ],
  dependencies: [
    .package(name: "GTMSessionFetcher", url: "https://github.com/google/gtm-session-fetcher", from: "1.5.0"),
    .package(name: "SwiftProtobuf", url: "https://github.com/apple/swift-protobuf", from: "1.15.0"),
  ],
  targets: [
    .target(
      name: "PromotedAIMetricsSDK",
      dependencies: [
        .product(name: "GTMSessionFetcherCore", package: "GTMSessionFetcher"),
        "SwiftProtobuf",
        "SchemaProtosSwift",
      ]),

    .testTarget(
      name: "PromotedAIMetricsSDKTests",
      dependencies: [
        "PromotedAIMetricsSDK"
      ]),
    
    // Each client opts in to either Objective C/Cocoapods or Swift/Swift PM.
    // This package should only contain clients who use Swift PM.

    // Base proto library. Don't include any client-specific protos.
    .target(
      name: "SchemaProtosSwift",
      dependencies: [
        "SwiftProtobuf",
      ],
      path: "Sources/SchemaProtos/swift",
      exclude: [
        "objc",
      ],
      sources: [
        "proto_common_common.pb.swift",
        "proto_event_event.pb.swift",
        "proto_pacing_pacing.pb.swift",
        "proto_promotion_promotion.pb.swift",
      ]),
    
    // Proto libraries per client.
    // These can't bring in SchemaProtosSwift as a dependency because the
    // autogenerated files don't import SchemaProtosSwift.
    .target(
      name: "PangeaSchemaProtosSwift",
      dependencies: [
        "SchemaProtosSwift",
      ],
      path: "Sources/SchemaProtos/swift",
      sources: [
        "proto_pangea_event_event.pb.swift",
      ]),
    .target(
      name: "QueenlySchemaProtosSwift",
      dependencies: [
        "SchemaProtosSwift",
      ],
      path: "Sources/SchemaProtos/swift",
      sources: [
        "proto_queenly_content_content.pb.swift",
        "proto_queenly_event_event.pb.swift",
      ]),
  ]
)
