// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/pacing/pacing.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PROEntityPath;
@class PROPacingAccount;
@class PROPacingCampaign;
GPB_ENUM_FWD_DECLARE(PROCurrencyCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PROPacingPacingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface PROPacingPacingRoot : GPBRootObject
@end

#pragma mark - PROPacingAccount

typedef GPB_ENUM(PROPacingAccount_FieldNumber) {
  PROPacingAccount_FieldNumber_CurrencyCode = 2,
};

GPB_FINAL @interface PROPacingAccount : GPBMessage

/** Status status = 1; ? */
@property(nonatomic, readwrite) enum PROCurrencyCode currencyCode;

@end

/**
 * Fetches the raw value of a @c PROPacingAccount's @c currencyCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PROPacingAccount_CurrencyCode_RawValue(PROPacingAccount *message);
/**
 * Sets the raw value of an @c PROPacingAccount's @c currencyCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPROPacingAccount_CurrencyCode_RawValue(PROPacingAccount *message, int32_t value);

#pragma mark - PROPacingCampaign

typedef GPB_ENUM(PROPacingCampaign_FieldNumber) {
  PROPacingCampaign_FieldNumber_DailyBudgetAmount = 2,
};

GPB_FINAL @interface PROPacingCampaign : GPBMessage

/** Status status = 1; ? */
@property(nonatomic, readwrite) double dailyBudgetAmount;

@end

#pragma mark - PROPacingFlatPacingCampaign

typedef GPB_ENUM(PROPacingFlatPacingCampaign_FieldNumber) {
  PROPacingFlatPacingCampaign_FieldNumber_EntityPath = 1,
  PROPacingFlatPacingCampaign_FieldNumber_Account = 4,
  PROPacingFlatPacingCampaign_FieldNumber_Campaign = 5,
};

GPB_FINAL @interface PROPacingFlatPacingCampaign : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PROEntityPath *entityPath;
/** Test to see if @c entityPath has been set. */
@property(nonatomic, readwrite) BOOL hasEntityPath;

/**
 * Platform platform = 2;
 * Customer customer = 3;
 **/
@property(nonatomic, readwrite, strong, null_resettable) PROPacingAccount *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, strong, null_resettable) PROPacingCampaign *campaign;
/** Test to see if @c campaign has been set. */
@property(nonatomic, readwrite) BOOL hasCampaign;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
