name: cocoapods

on:
  push:
  pull_request:

jobs:
  pod-lib-lint:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: actions/setup-xcode@v1
      with:
        xcode-version: 13.2.1
    - name: Lint
      run: pod lib lint --verbose
