name: cocoapods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pod-lib-lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Lint
      run: pod lib lint --verbose
