name: cocoapods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pod-lib-lint:
    strategy:
      matrix:
        macos: [macos-latest]
        xcode: [latest]
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v1.1.2
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Lint
      run: pod lib lint --verbose
