name: cocoapods_deploy

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
