name: cocoapods

on:
  push:
  pull_request:

jobs:
  pod-lib-lint:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
    - name: Lint
      run: pod lib lint --verbose
