name: ios-metrics-sdk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-xcode-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
  build-and-test-xcode-11:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v1.1.2
      with:
        xcode-version: '11.7'
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
