name: swiftpm

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
    # - name: Build
    #   run: xcodebuild -scheme PromotedAIMetricsSDK-Package build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
    - name: Test
      run: xcodebuild -scheme PromotedAIMetricsSDK-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
