name: swiftpm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme PromotedAIMetricsSDK-Package build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
    - name: Test
      run: xcodebuild -scheme PromotedAIMetricsSDK-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
